server:
  servlet:
    context-path: /


spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      org.hibernate.flushMode: MANUAL

